### ISSUE TITLE
Can't run python3 setup.py install in MacOS - Possible solution

### ISSUE THREAD

**Issue by linhnph05** [noraj/flask-session-cookie-manager#12]
When I try to run `python3 setup.py install`, it get this error:

> error: Multiple top-level modules discovered in a flat-layout: ['flask_session_cookie_manager2', 'flask_session_cookie_manager3'].
To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.
If you are trying to create a single distribution with multiple modules
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:
> 1. set up custom discovery (`find` directive with `include` or `exclude`)
> 2. use a `src-layout`
> 3. explicitly set `py_modules` or `packages` with a list of names
To find more information, look for "package discovery" on setuptools docs.

My fix to make it works is add this parameter in `setup()` function in `setup.py`: `py_modules=[]`, after that the setup is successful

**Comment by noraj** [comment]
Thanks for your report.
It's fixed now. Also use `python -m pip install .` rather than `python3 setup.py install`. I updated the README.
