### ISSUE TITLE
My late response

### ISSUE THREAD

**Issue by TAbdiukov** [noraj/flask-session-cookie-manager#2]
Hey! Sorry for a late response, I was busy with exams.

Sadly, as for Python 2, I have no idea what needs to be done. 

Mind you publish code onto Pypi? Thanks

I also noticed you've done substantial changes to the code! Great? How sure if its a bug or not (if it is, it's probably some of my mistakes), but for Python 3.6+, when trying to decode, it returns bytestream, not String

thanks

**Comment by noraj** [comment]
You mean:

```
python flask_session_cookie_manager3.py decode -c 'eyJudW1iZXIiOnsiIGIiOiJNekkyTkRFd01ETXhOVEExIn0sInVzZXJuYW1lIjp7IiBiIjoiWVdSdGFXND0ifX0.DE2iRA.ig5KSlnmsDH4uhDpmsFRPupB5Vw' -s '.{y]tR&sp&77RdO~u3@XAh#TalD@Oh~yOF_51H(QV};K|ghT^d'
{'number': b'326410031505', 'username': b'admin'}
```

Yeah, it normal and was already like that before. i'll sure push.

**Comment by noraj** [comment]
@TAbdiukov https://pypi.org/project/flask-session-cookie-manager/
