### ISSUE TITLE
py3 运行出错

### ISSUE THREAD

**Issue by left2333345** [noraj/flask-session-cookie-manager#4]
你好，在py3.9的环境下，运行报错：[Encoding error] dictionary update sequence element #0 has length 1; 2 is required

可以看下是什么问题么，非常感谢

**Comment by noraj** [comment]
Hi @left2333345 

```
$ python --version
Python 3.9.6

$ python flask_session_cookie_manager3.py decode -c 'eyJudW1iZXIiOnsiIGIiOiJNekkyTkRFd01ETXhOVEExIn0sInVzZXJuYW1lIjp7IiBiIjoiWVdSdGFXND0ifX0.DE2iRA.ig5KSlnmsDH4uhDpmsFRPupB5Vw' -s '.{y]tR&sp&77RdO~u3@XAh#TalD@Oh~yOF_51H(QV};K|ghT^d'
{'number': b'326410031505', 'username': b'admin'}

$ python flask_session_cookie_manager3.py encode -s '.{y]tR&sp&77RdO~u3@XAh#TalD@Oh~yOF_51H(QV};K|ghT^d' -t '{"number":"326410031505","username":"admin"}'
eyJudW1iZXIiOiIzMjY0MTAwMzE1MDUiLCJ1c2VybmFtZSI6ImFkbWluIn0.YQvCsQ.IDuYIDtSLEiDUWKZwYv0UJf1qNc
```

For me everything is running fine under python 3.9.

Could you provide your version of python, the command you're trying to run, more details about your context. And please share me all this in english.

**Comment by noraj** [comment]
No news.

**Comment by criticalstop** [comment]
Hi，I encountered the same issue today while using python 3.11. Seems python throws a ValueError when it converts string to dict by using dict() function. After replacing dict() to eval() in line 38 and line 83, the program works perfectly.
Thank you for your great work.

**Comment by noraj** [comment]
@criticalstop Could you share the command/payload?

**Comment by criticalstop** [comment]
> @criticalstop Could you share the command/payload?

Sure, you can check my modification here:https://www.diffchecker.com/ujQ0wNnG

**Comment by noraj** [comment]
> > @criticalstop Could you share the command/payload?
> 
> Sure, you can check my modification here:https://www.diffchecker.com/ujQ0wNnG

No, I meant could you share the cookie (payload) that was generating the error or the full comand you used generating the error. Not the patch you did.
