### ISSUE TITLE
Question regarding decoding and encoding

### ISSUE THREAD

**Issue by stevekangLunit** [noraj/flask-session-cookie-manager#9]
Hi. I successfully decoded a test cookie and the result was as follows : 

1. b'{"_fresh":true,"_id":{" b":"SOMEVALUES="},"csrf_token":{" b":"SOMEVALUES=="},"user_id":"SOMEINT"}'

However, when I try to re-encode it, following error occurred : 

 error: unrecognized arguments: b_id:{ b:SOMEVALUES=} bcsrf_token:{ b:SOMEVALUES==} buser_id:SOMEINT

I removed the "b" values like below

2. {"_fresh":true,"_id":{" b":"SOMEVALUES="},"csrf_token":{" b":"SOMEVALUES=="},"user_id":"SOMEINT"}

However, this does not give me exact cookie value that I input in decoding stage. 

How can I reproduce the same cookie with value from 1. ?

Thank you

**Comment by noraj** [comment]
Advice n°1: Read the [README](https://github.com/noraj/flask-session-cookie-manager/blob/master/README.md)

```
$ key='.{y]tR&sp&77RdO~u3@XAh#TalD@Oh~yOF_51H(QV};K|ghT^d'

$ cookie=$(flask-session-cookie-manager3 encode -s $key -t '{"number":"326410031505","username":"admin"}')

$ echo $cookie            
eyJudW1iZXIiOiIzMjY0MTAwMzE1MDUiLCJ1c2VybmFtZSI6ImFkbWluIn0.YnvS5g.ILOJw198xn54t7BsJ_KlQlKXBew

$ flask-session-cookie-manager3 decode -c $cookie -s $key        
{'number': '326410031505', 'username': 'admin'}

$ flask-session-cookie-manager3 decode -c $cookie        
b'{"number":"326410031505","username":"admin"}'

$ cookie2=$(flask-session-cookie-manager2 encode -s $key -t '{"number":"326410031505","username":"admin"}')

$ echo $cookie2
eyJudW1iZXIiOnsiIGIiOiJNekkyTkRFd01ETXhOVEExIn0sInVzZXJuYW1lIjp7IiBiIjoiWVdSdGFXND0ifX0.YnvTpA.YqsY5Kz9fVmLPu2hTOwtjAzLRbk

$ flask-session-cookie-manager2 decode -c $cookie2 -s $key 
{u'username': 'admin', u'number': '326410031505'}

$ flask-session-cookie-manager2 decode -c $cookie2         
{"number":{" b":"MzI2NDEwMDMxNTA1"},"username":{" b":"YWRtaW4="}}
```

Advice n°2: Use python 3 rather than python2 which is deprecated

Your cookie looks bad because 1) it was decoded with python 2 and 2) because it was decoded without a secret key

Decoding of the same cookie:

```bash
# python 3 with secret key
{'number': '326410031505', 'username': 'admin'}
# python 3 without secret key
b'{"number":"326410031505","username":"admin"}'
# python 2 with secret key
{u'username': 'admin', u'number': '326410031505'}
# python 2 without secret key
{"number":{" b":"MzI2NDEwMDMxNTA1"},"username":{" b":"YWRtaW4="}}
```

So you will have not only to remove the b's but also to base64 decode the values and de-bloat the dict.

Advice n°3: you can't craft a cookie without a secret key anyway
